/*
LICENCIA JOSE JAVIER BO
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
Lista de paquetes:
 */
package ud1_ejer9.gui;

/**
 *
 * @author Jose Javier BO
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        origButtonGroup = new javax.swing.ButtonGroup();
        copyButtonGroup = new javax.swing.ButtonGroup();
        lbOriginal = new javax.swing.JLabel();
        origRb1 = new javax.swing.JRadioButton();
        origRb2 = new javax.swing.JRadioButton();
        origRb3 = new javax.swing.JRadioButton();
        origCb1 = new javax.swing.JCheckBox();
        origCb2 = new javax.swing.JCheckBox();
        origCb3 = new javax.swing.JCheckBox();
        origTexto = new javax.swing.JTextField();
        origComboBox = new javax.swing.JComboBox<>();
        origSpinner = new javax.swing.JSpinner();
        jSeparator1 = new javax.swing.JSeparator();
        lbOriginal1 = new javax.swing.JLabel();
        copyRb1 = new javax.swing.JRadioButton();
        copyRb2 = new javax.swing.JRadioButton();
        copyRb3 = new javax.swing.JRadioButton();
        copyCb1 = new javax.swing.JCheckBox();
        copyCb2 = new javax.swing.JCheckBox();
        copyCb3 = new javax.swing.JCheckBox();
        copyTexto = new javax.swing.JTextField();
        copyComboBox = new javax.swing.JComboBox<>();
        copySpinner = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbOriginal.setText("Original");

        origButtonGroup.add(origRb1);
        origRb1.setText("Opcion 1");
        origRb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                origRb1ActionPerformed(evt);
            }
        });

        origButtonGroup.add(origRb2);
        origRb2.setText("Opcion 2");
        origRb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                origRb2ActionPerformed(evt);
            }
        });

        origButtonGroup.add(origRb3);
        origRb3.setText("Opcion 3");
        origRb3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                origRb3ActionPerformed(evt);
            }
        });

        origCb1.setText("Opcion 4");
        origCb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                origCb1ActionPerformed(evt);
            }
        });

        origCb2.setText("Opcion 5");
        origCb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                origCb2ActionPerformed(evt);
            }
        });

        origCb3.setText("Opcion 6");
        origCb3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                origCb3ActionPerformed(evt);
            }
        });

        origTexto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                origTextoKeyReleased(evt);
            }
        });

        origComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        origComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                origComboBoxActionPerformed(evt);
            }
        });

        origSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                origSpinnerStateChanged(evt);
            }
        });

        lbOriginal1.setText("Original");

        copyButtonGroup.add(copyRb1);
        copyRb1.setText("Opcion 1");
        copyRb1.setEnabled(false);

        copyButtonGroup.add(copyRb2);
        copyRb2.setText("Opcion 2");
        copyRb2.setEnabled(false);

        copyButtonGroup.add(copyRb3);
        copyRb3.setText("Opcion 3");
        copyRb3.setEnabled(false);

        copyCb1.setText("Opcion 4");
        copyCb1.setEnabled(false);

        copyCb2.setText("Opcion 5");
        copyCb2.setEnabled(false);

        copyCb3.setText("Opcion 6");
        copyCb3.setEnabled(false);

        copyTexto.setEnabled(false);

        copyComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        copyComboBox.setEnabled(false);

        copySpinner.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(origRb1)
                                        .addGap(37, 37, 37)
                                        .addComponent(origCb1))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(origRb3)
                                            .addGap(37, 37, 37)
                                            .addComponent(origCb3))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(origRb2)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(origCb2))))
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(origComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, 101, Short.MAX_VALUE)
                                    .addComponent(origSpinner, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(origTexto)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lbOriginal)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 13, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(copyRb1)
                                        .addGap(37, 37, 37)
                                        .addComponent(copyCb1))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(copyRb3)
                                            .addGap(37, 37, 37)
                                            .addComponent(copyCb3))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(copyRb2)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(copyCb2))))
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(copyComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(copySpinner, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(copyTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lbOriginal1))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbOriginal)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(origCb1)
                    .addComponent(origTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(origRb1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(origCb2)
                            .addComponent(origComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(origSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(origRb2)
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(origRb3)
                            .addComponent(origCb3))))
                .addGap(30, 30, 30)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbOriginal1)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(copyCb1)
                    .addComponent(copyTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(copyRb1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(copyCb2)
                            .addComponent(copyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(copySpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(copyRb2)
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(copyRb3)
                            .addComponent(copyCb3))))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void origRb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_origRb2ActionPerformed
        copyRb2.setSelected(true);
    }//GEN-LAST:event_origRb2ActionPerformed

    private void origRb3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_origRb3ActionPerformed
        copyRb3.setSelected(true);
    }//GEN-LAST:event_origRb3ActionPerformed

    private void origCb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_origCb1ActionPerformed
        copyCb1.setSelected(origCb1.isSelected());
    }//GEN-LAST:event_origCb1ActionPerformed

    private void origCb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_origCb2ActionPerformed
        copyCb2.setSelected(origCb2.isSelected());
    }//GEN-LAST:event_origCb2ActionPerformed

    private void origCb3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_origCb3ActionPerformed
        copyCb3.setSelected(origCb3.isSelected());
    }//GEN-LAST:event_origCb3ActionPerformed

    private void origTextoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_origTextoKeyReleased
        copyTexto.setText(origTexto.getText());
    }//GEN-LAST:event_origTextoKeyReleased

    private void origComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_origComboBoxActionPerformed
        copyComboBox.setSelectedIndex(origComboBox.getSelectedIndex());
    }//GEN-LAST:event_origComboBoxActionPerformed

    private void origSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_origSpinnerStateChanged
        copySpinner.setValue(origSpinner.getValue());
    }//GEN-LAST:event_origSpinnerStateChanged

    private void origRb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_origRb1ActionPerformed
        copyRb1.setSelected(true);
    }//GEN-LAST:event_origRb1ActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup copyButtonGroup;
    private javax.swing.JCheckBox copyCb1;
    private javax.swing.JCheckBox copyCb2;
    private javax.swing.JCheckBox copyCb3;
    private javax.swing.JComboBox<String> copyComboBox;
    private javax.swing.JRadioButton copyRb1;
    private javax.swing.JRadioButton copyRb2;
    private javax.swing.JRadioButton copyRb3;
    private javax.swing.JSpinner copySpinner;
    private javax.swing.JTextField copyTexto;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbOriginal;
    private javax.swing.JLabel lbOriginal1;
    private javax.swing.ButtonGroup origButtonGroup;
    private javax.swing.JCheckBox origCb1;
    private javax.swing.JCheckBox origCb2;
    private javax.swing.JCheckBox origCb3;
    private javax.swing.JComboBox<String> origComboBox;
    private javax.swing.JRadioButton origRb1;
    private javax.swing.JRadioButton origRb2;
    private javax.swing.JRadioButton origRb3;
    private javax.swing.JSpinner origSpinner;
    private javax.swing.JTextField origTexto;
    // End of variables declaration//GEN-END:variables
}
